#include <cstring>
#include <cstdlib>
#include <ctime>
#include <iostream>
#include <string>
#include <fstream>
#include <vector>

#include <QApplication>
#include <QMainWindow>
#include <QDialog>
#include <QStatusBar>
#include <QListView>
#include <QStandardItemModel>
#include <QItemSelectionModel>
#include <QTextEdit>
#include <QMenuBar>
#include <QMenu>
#include <QAction>
#include <QMessageBox>
#include <QTimer>
#include <QSystemTrayIcon>
#include <QFile>
#include <QDir>
#include <QTextCharFormat>
#include <QTextCursor>
#include <QIcon>
#include <QScreen>
#include <QBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QCloseEvent>
#include <QWindowStateChangeEvent>

using namespace std;

#include "prayer.h"
#include "easter.h"
#include "ui_prayer-clock.h" // Generated by cmake

class PrayerClock : public QMainWindow, private Ui::MainWindow {
  Q_OBJECT

public:
  PrayerClock(QWidget *parent = nullptr);
  ~PrayerClock() override;

protected:
  void changeEvent(QEvent *event) override;

private slots:
  void showPrayer();
  void quitApp();
  void timeout();
  void trayClicked();
  // void minimizeWindow(QWindowStateChangeEvent* event);
  void aboutDialogShow();
  void aboutDialogClosed(int result);
  bool deleteEventHandler(QCloseEvent* event);

private:
  Prayers* prayers;
  QStandardItemModel* prayerModel;
  QItemSelectionModel* selectModel;
  QTextEdit* prayerView;
  QMainWindow* mainWindow; // 指向自身
  QDialog* aboutDialog;
  QStatusBar* statusBar;
  bool easterSeason;
  QSystemTrayIcon* trayIcon;

  void updateTimeDisplay();
  void loadPrayersToListView();
  void checkSpecialOccasion(const DateTime& today);
  Ui::MainWindow *ui;
};
